- name: configuring mysql
  become: yes
  hosts: mysql
  tasks:
    - name: Install mysql 8.x
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: start & enable service
      ansible.builtin.service:
        state: started
        enabled: yes

    - name: Ensure MySQL root password is set
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "RoboShop@1"
        login_user: root
        login_password: ""
        state: present

    


